language: java
install: true
addons:
  sonarqube:
    token:
      secure: "3b7b0b823020310b84f8f8f7d154e0d66b5920b6"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

